name: "Base repo setup"
description: "Run basic repo setup commands"
inputs:
  token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
      with:
        install: true
        cache: true
        github_token: ${{ inputs.token }}

    - name: Get pnpm store directory
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Prepare deps
      shell: bash
      env:
        FORCE_COLOR: 0
      run: pnpm install --frozen-lockfile
