packages:
  - packages/*
  - examples/*
  - docs/*

catalog:
  '@tanstack/react-query': 5.90.10
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  '@urql/core': 6.0.1
  gql.tada: 1.9.0
  react: 19.2.0
  react-dom: 19.2.0

minimumReleaseAge: 1440

overrides:
  hono@<4.11.4: '>=4.11.4'
  lodash-es@>=4.0.0 <=4.17.22: '>=4.17.23'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  react-router@>=7.0.0 <7.12.0: '>=7.12.0'
