packages:
  - packages/*
  - examples/*
  - site

catalog:
  '@tanstack/react-query': 5.90.10
  '@types/react': ^19.2.0
  '@types/react-dom': ^19.2.0
  gql.tada: 1.9.0
  react: 19.2.0
  react-dom: 19.2.0

minimumReleaseAge: 1440

overrides:
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  react-router@>=7.0.0 <7.12.0: '>=7.12.0'
